targets:
- company: Microsoft
  ats_type: workday
  workday_company_id: microsoft
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Redmond
  - New York
  - Remote
  categories:
  - ml_ai
  - cybersecurity
  - data_science
  - platform_security
- company: Amazon
  ats_type: workday
  workday_company_id: amazon
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Seattle
  - Bay Area
  - Boston
  - New York
  - Austin
  - Remote
  categories:
  - ml_ai
  - data_science
  - data_engineering
  - cybersecurity
  - ml_platform
  - platform_security
- company: Cloudflare
  ats_type: workday
  workday_company_id: cloudflare
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - San Francisco
  - Austin
  - New York
  - Remote
  categories:
  - platform_security
  - cybersecurity
  - data_engineering
  - ml_ai
  - ml_platform
  - data_science
- company: Block (Square)
  ats_type: workday
  workday_company_id: block
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Bay Area
  - New York
  - Seattle
  - Remote
  categories:
  - ml_ai
  - data_science
  - data_engineering
  - cybersecurity
  - ml_platform
  - platform_security
- company: DoorDash
  ats_type: workday
  workday_company_id: doordash
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Bay Area
  - New York
  - Seattle
  - Remote
  categories:
  - ml_ai
  - data_science
  - data_engineering
  - platform_security
  - ml_platform
  - cybersecurity
- company: Wayfair
  ats_type: workday
  workday_company_id: wayfair
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Boston
  - Austin
  - Remote
  categories:
  - ml_ai
  - data_science
  - data_engineering
  - platform_security
  - ml_platform
  - cybersecurity
- company: Belvedere Trading
  ats_type: lever
  careers_url: https://jobs.lever.co/belvederetrading
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - data_engineering
- company: Voleon Group
  ats_type: lever
  careers_url: https://jobs.lever.co/voleon
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - ml_ai
  - data_science
  - software_engineering
- company: Feedzai
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/feedzai
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - data_science
  - cybersecurity
- company: Forter
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/forter
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - data_science
  - cybersecurity
- company: Riskified
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/riskified
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - data_science
- company: Arkose Labs
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/arkoselabs
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - cybersecurity
- company: Finix
  ats_type: lever
  careers_url: https://jobs.lever.co/finix
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - backend
- company: Pagaya
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/pagaya
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - data_science
- company: Payoneer
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/payoneer
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - backend
- company: Melio
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/melio
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - backend
- company: Bill.com
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/billcom
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - backend
  - data_engineering
- company: Recorded Future
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/recordedfuture
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - cybersecurity
  - ml_ai
  - data_science
- company: ThreatConnect
  ats_type: lever
  careers_url: https://jobs.lever.co/threatconnect
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - cybersecurity
  - software_engineering
- company: Anomali
  ats_type: lever
  careers_url: https://jobs.lever.co/anomali
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - cybersecurity
  - ml_ai
- company: KnowBe4
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/knowbe4
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - cybersecurity
  - software_engineering
- company: Dragos
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/dragos
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - cybersecurity
  - software_engineering
- company: Tanium
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/tanium
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - cybersecurity
  - software_engineering
- company: Orca Security
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/orcasecurity
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - cybersecurity
  - software_engineering
  - ml_ai
- company: Domo
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/domo
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - data_engineering
- company: Sisense
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/sisense
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - data_engineering
- company: Collibra
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/collibra
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - data_engineering
- company: BigID
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/bigid
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - data_engineering
  - cybersecurity
- company: StockX
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/stockx
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
- company: Poshmark
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/poshmark
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
- company: ComplyAdvantage
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/complyadvantage
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - data_science
- company: Jumio
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/jumio
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - cybersecurity
- company: Persona
  ats_type: lever
  careers_url: https://jobs.lever.co/persona
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - cybersecurity
- company: Alloy
  ats_type: lever
  careers_url: https://jobs.lever.co/alloy
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
- company: MoneyLion
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/moneylion
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
- company: Prosper
  ats_type: lever
  careers_url: https://jobs.lever.co/prosper
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
- company: Upstart
  ats_type: greenhouse
  careers_url: https://boards.greenhouse.io/upstart
  roles_include:
  - intern
  - summer 2026
  - internship
  locations:
  - Remote
  - New York
  - Bay Area
  - Seattle
  - Boston
  - Austin
  - Chicago
  categories:
  - software_engineering
  - ml_ai
  - data_science
